# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  website-scan:
    runs-on: ubuntu-latest
    name: DAST (Dynamic Application Security Testing)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Action Full Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: owasp/zap2docker-stable
          target: ${{ secrets.WEBSITE_URL }}
          cmd_options: >
            -a
            -j
            -z "
            -config alert.maxInstances=0
            -config view.locale=ja_JP
            "
